import { ArrowUpRight, Clock3, Mail, MapPin, MessageCircle, Navigation, Phone } from 'lucide-react'
import Button from '../components/Button.jsx'
import SectionHeader from '../components/SectionHeader.jsx'
import { clinic } from '../data/demoData.js'

function Contact() {
  return <><section className="page-hero page-hero-short"><div className="wrap page-hero-inner"><span className="eyebrow">We’re easy to find</span><h1>Let’s talk<br /><em>about your smile.</em></h1><p>Questions about a visit? Our demo team details are gathered here for easy reference.</p></div></section><section className="contact-section section-space"><div className="wrap contact-layout"><div className="contact-main"><SectionHeader eyebrow="Get in touch" title="We’d love to hear from you." description="The contact details on this page are fictional examples and are not connected to a real clinic." /><div className="contact-actions"><Button href={`tel:${clinic.phone.replaceAll(/[^+\d]/g, '')}`}><Phone size={17} /> Call the clinic</Button><Button href={clinic.whatsapp} variant="outline" target="_blank" rel="noreferrer"><MessageCircle size={17} /> WhatsApp</Button></div><div className="contact-details"><a href={clinic.mapUrl} target="_blank" rel="noreferrer"><span className="contact-icon"><MapPin size={20} /></span><span><small>Visit us</small><strong>{clinic.address}</strong></span><ArrowUpRight size={16} /></a><a href={`tel:${clinic.phone.replaceAll(/[^+\d]/g, '')}`}><span className="contact-icon"><Phone size={20} /></span><span><small>Call us</small><strong>{clinic.phone}</strong></span><ArrowUpRight size={16} /></a><a href={`mailto:${clinic.email}`}><span className="contact-icon"><Mail size={20} /></span><span><small>Email</small><strong>{clinic.email}</strong></span><ArrowUpRight size={16} /></a></div><div className="hours-panel"><h2><Clock3 size={19} /> Opening hours</h2>{clinic.hours.map((item) => <div className="hours-row" key={item.day}><span>{item.day}</span><strong>{item.time}</strong></div>)}</div></div><div className="map-panel"><div className="map-surface"><div className="map-grid-lines" /><span className="map-road road-a" /><span className="map-road road-b" /><span className="map-park">WILLOW CREEK<br />GARDEN</span><span className="map-pin"><MapPin size={22} fill="currentColor" /></span><span className="map-label">LUMINA DENTAL</span><span className="map-map-caption">PORTLAND · OREGON</span></div><div className="map-panel-footer"><div><span className="eyebrow">Find your way</span><p>{clinic.address}</p></div><a className="directions-link" href={clinic.mapUrl} target="_blank" rel="noreferrer"><Navigation size={17} /> Directions</a></div><p className="map-disclaimer">Illustrative map placeholder. Demo address only.</p></div></div></section><section className="contact-bottom"><div className="wrap contact-bottom-inner"><div><span className="eyebrow">First visits are conversations</span><h2>Not sure where to begin?</h2><p>Tell us what’s on your mind and we’ll help you find the right next step.</p></div><Button to="/appointment" variant="light" icon>Request a visit</Button></div></section></>
}

export default Contact