import { ArrowDownRight, ArrowRight, BadgeCheck, CalendarDays, HeartHandshake, Phone, Sparkles, Stethoscope, Waves } from 'lucide-react'
import { Link } from 'react-router-dom'
import Button from '../components/Button.jsx'
import DentistCard from '../components/DentistCard.jsx'
import SectionHeader from '../components/SectionHeader.jsx'
import ServiceCard from '../components/ServiceCard.jsx'
import { clinic, dentists, promotion, services, testimonials } from '../data/demoData.js'

const features = [
  { title: 'Experienced dentists', detail: 'A thoughtful team with different areas of focus.', icon: Stethoscope },
  { title: 'Modern equipment', detail: 'Current tools support careful, informed care.', icon: Sparkles },
  { title: 'Personalized care', detail: 'A plan shaped around your needs and questions.', icon: HeartHandshake },
  { title: 'Convenient visits', detail: 'Clear scheduling and a team ready to help.', icon: CalendarDays },
]

function Home() {
  return <>
    <section className="hero-section"><div className="hero-wrap wrap"><div className="hero-copy"><span className="eyebrow"><span className="eyebrow-dot" /> A calmer kind of dental care</span><h1>Your smile deserves <em>exceptional care.</em></h1><p>Modern dental care delivered by experienced professionals in a comfortable and welcoming environment.</p><div className="hero-actions"><Button to="/appointment" icon>Book an appointment</Button><a className="call-link" href={`tel:${clinic.phone.replaceAll(/[^+\d]/g, '')}`}><span className="call-icon"><Phone size={19} /></span><span><small>Have a question?</small><strong>{clinic.phone}</strong></span></a></div><div className="hero-proof"><div className="proof-avatars" aria-hidden="true"><span>M</span><span>J</span><span>A</span></div><p><strong>A more considered visit.</strong><br />Meet a team that takes time to listen.</p></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1500&q=90" alt="Bright, modern dental care room" fetchPriority="high" /><div className="hero-image-caption"><span className="caption-mark"><Sparkles size={19} /></span><span><strong>Care that feels different</strong><small>From your first hello to your follow-up</small></span></div><span className="hero-side-note">PORTLAND · OREGON</span></div><a className="hero-scroll" href="#welcome"><span>Scroll to explore</span><ArrowDownRight size={16} /></a></div></section>
    <section className="welcome-strip" id="welcome"><div className="wrap welcome-inner"><p><span className="eyebrow">A note from our team</span><strong>Good care starts with a good conversation.</strong></p><p>At Lumina, we make room for questions, explain your options, and help you feel at home in the chair.</p><Link to="/about" className="text-link">Get to know us <ArrowRight size={16} /></Link></div></section>
    <section className="feature-section section-space"><div className="wrap feature-grid">{features.map(({ title, detail, icon: Icon }, index) => <article className="feature-item" key={title}><span className="feature-index">0{index + 1}</span><span className="feature-icon"><Icon size={21} strokeWidth={1.6} /></span><h2>{title}</h2><p>{detail}</p></article>)}</div></section>
    <section className="services-section section-space"><div className="wrap"><div className="section-row"><SectionHeader eyebrow="Care, thoughtfully considered" title="Our dental services" description="From the everyday to the more involved, find care that meets you where you are." /><Button to="/services" variant="outline" icon>All services</Button></div><div className="service-grid">{services.map((service) => <ServiceCard key={service.id} service={service} />)}</div></div></section>
    <section className="team-section section-space"><div className="wrap"><div className="section-row"><SectionHeader eyebrow="People make the practice" title="Meet your care team" description="Get to know our fictional demo dentists and the different perspectives they bring." /><Button to="/dentists" variant="outline" icon>Meet the team</Button></div><div className="dentist-grid">{dentists.slice(0, 3).map((dentist) => <DentistCard key={dentist.id} dentist={dentist} />)}</div></div></section>
    <section className="approach-section"><div className="wrap approach-grid"><div className="approach-image"><img src="https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=1200&q=85" alt="A welcoming modern dental treatment space" loading="lazy" /><span>Designed for your comfort</span></div><div className="approach-copy"><span className="eyebrow">Why Lumina</span><h2>Care that considers the whole person.</h2><p>Dental care should feel collaborative, never rushed. We bring modern tools and a human touch together so you can make informed decisions with confidence.</p><ul>{['Experienced professionals', 'Modern technology, used with purpose', 'Transparent treatment conversations', 'A comfortable, welcoming environment'].map((item) => <li key={item}><BadgeCheck size={18} />{item}</li>)}</ul><Button to="/about" variant="outline" icon>Our approach</Button></div></div></section>
    <section className="offer-section section-space"><div className="wrap offer-panel"><div className="offer-copy"><span className="eyebrow">{promotion.label}</span><h2>{promotion.title}</h2><p>{promotion.description}</p><span className="offer-note">{promotion.note}</span><Button to="/appointment" variant="light">Explore the offer <ArrowRight size={16} /></Button></div><div className="offer-art" aria-hidden="true"><span className="offer-orbit orbit-one" /><span className="offer-orbit orbit-two" /><span className="offer-number">20<sup>%</sup></span><span className="offer-caption">A little more<br />reason to smile</span><Waves className="offer-wave" size={88} strokeWidth={0.7} /></div></div></section>
    <section className="testimonial-section section-space"><div className="wrap"><SectionHeader eyebrow="Kind words, just for the demo" title="A little reassurance goes a long way." description="These fictional patient notes are here to show how reviews may appear." align="center" /><div className="testimonial-grid">{testimonials.map((item, index) => <article className="testimonial-card" key={`${item.context}-${index}`}><div className="stars" aria-label={`${item.rating} out of 5 stars`}>{Array.from({ length: item.rating }, (_, star) => <span key={star}>★</span>)}</div><blockquote>“{item.quote}”</blockquote><div className="testimonial-by"><span className="testimonial-avatar">{index === 2 ? 'P' : 'D'}</span><span><strong>{item.name}</strong><small>{item.context}</small></span><span className="demo-tag">Demo</span></div></article>)}</div></div></section>
    <section className="appointment-banner"><div className="wrap appointment-banner-inner"><div><span className="eyebrow">A good place to start</span><h2>Ready to take care<br />of your smile?</h2><p>Book your dental appointment today.</p></div><Button to="/appointment" variant="light" icon>Book an appointment</Button><span className="banner-spark" aria-hidden="true">✳</span></div></section>
  </>
}

export default Home