import { ArrowLeft, BadgeCheck, Clock3, CircleHelp, ClipboardList } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import Button from '../components/Button.jsx'
import { services } from '../data/demoData.js'

function ServiceDetails() {
  const { id } = useParams()
  const service = services.find((item) => item.id === id)
  if (!service) return <section className="empty-page wrap"><h1>That service isn’t here.</h1><Link className="text-link" to="/services"><ArrowLeft size={16} /> Back to services</Link></section>
  return <><div className="breadcrumbs wrap"><Link to="/services"><ArrowLeft size={15} /> All services</Link><span>/</span><span>{service.title}</span></div><section className="detail-hero"><div className="wrap detail-hero-grid"><div className="detail-hero-copy"><span className="eyebrow">{service.category} care</span><h1>{service.title}</h1><p>{service.shortDescription}</p><div className="detail-quick-facts"><span><Clock3 size={17} /> Typical visit: {service.duration}</span><span><ClipboardList size={17} /> {service.price}</span></div><Button to={`/appointment?service=${service.id}`} icon>Request this appointment</Button><small className="demo-note">General information only. Your dentist can discuss options after an assessment.</small></div><img className="detail-hero-image" src={service.image} alt={`Illustrative photo for ${service.title}`} /></div></section><section className="detail-content-section section-space"><div className="wrap detail-content-grid"><div className="detail-main"><span className="eyebrow">At a glance</span><h2>What to expect</h2><p>{service.description}</p><div className="detail-list-block"><h3><BadgeCheck size={19} /> Potential benefits</h3><ul>{service.benefits.map((benefit) => <li key={benefit}>{benefit}</li>)}</ul></div><div className="detail-list-block"><h3><ClipboardList size={19} /> A typical visit</h3><ol>{service.procedure.map((step) => <li key={step}>{step}</li>)}</ol></div><div className="detail-two-col"><div><h3>Before your visit</h3><p>{service.preparation}</p></div><div><h3>Aftercare</h3><p>{service.aftercare}</p></div></div><div className="faq-block"><h2><CircleHelp size={22} /> Common questions</h2>{service.faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div><aside className="detail-aside"><span className="eyebrow">Planning your visit</span><h2>{service.title}</h2><p>Every treatment discussion begins with a conversation and an assessment by your dentist.</p><div className="aside-fact"><span>Typical duration</span><strong>{service.duration}</strong></div><div className="aside-fact"><span>Fees</span><strong>{service.price}</strong></div><Button to={`/appointment?service=${service.id}`}>Request an appointment</Button><small>Demo page. Recommendations and fees depend on a dental assessment.</small></aside></div></section></>
}

export default ServiceDetails